name: Build and Run with pipe command

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build for production-pipe
      run: g++ -Wall -Wextra -o result ./main.c ./bms_sender.c ./bmsdata_func.c 
      
    - name: run
      run: ./result 20
 
