name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build for production
      run: g++ -Wall -Wextra -o production ./main.c ./bms_sender.c ./bmsdata_func.c 
      
    - name: run
      run: ./production 20
 
