name: Build and Run with pipe command

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build Sender for prod
      run: g++ -Wall -Wextra -o result ./main.c ./bms_sender.c ./bmsdata_func.c 
          
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Receiver for prod
      run: javac src/main/java/receiver/BmsReceiver.java
    - name: run
      run: ./result 20 | java -ea -cp "src" main.java.receiver.BmsReceiver
 
