name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install coverage tool
      run: sudo apt-get install -y gcovr

    - name: build for test
      run: g++ -DUNIT_TEST -Wall -Wextra -fprofile-arcs -ftest-coverage -o testchecker ./test_main.c ./bms_sender.c ./bmsdata_func_fake.c ./test_mocks.c
      
    - name: run
      run: ./testchecker

    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 1
    
    - name: build for production
      run: g++ -Wall -Wextra -o production ./main.c ./bms_sender.c ./bmsdata_func.c 
      
 
